# fly.toml
app = "demo-cg"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 5
    hard_limit = 10

  # Health check tuned to tolerate CPU spikes
  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "5s"
    grace_period = "30s"
